additional_feature_files: None
batch_size: 256
cache_data: true
cache_validation_data: false
camels_attributes:
- elev_mean
- slope_mean
- area_gages2
- frac_forest
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- soil_depth_pelletier
- soil_depth_statsgo
- soil_porosity
- soil_conductivity
- max_water_content
- sand_frac
- silt_frac
- clay_frac
- carbonate_rocks_frac
- geol_permeability
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
clip_gradient_norm: 1
data_dir: /publicdata/CAMELS
dataset: camels_us
device: cuda:0
dynamic_inputs:
- prcp(mm/day)_maurer_extended
- srad(W/m2)_maurer_extended
- tmax(C)_maurer_extended
- tmin(C)_maurer_extended
- vp(Pa)_maurer_extended
embedding_hiddens:
epochs: 30
experiment_name: cudalstm_maurer_seed404829
forcings:
- maurer_extended
h5_file: None
head: regression
hidden_size: 256
initial_forget_bias: 3
learning_rate:
  0: 0.001
  10: 0.0005
  25: 0.0001
log_interval: 5
log_tensorboard: true
loss: NSE
metrics:
model: cudalstm
num_workers: 16
optimizer: Adam
output_dropout: 0.4
predict_last_n: 1
run_dir: ensemble_input_new
save_validation_results: false
save_weights_every: 1
scaler_file: None
seed: 404829
seq_length: 365
static_inputs: []
target_variable:
- QObs(mm/d)
test_basin_file: data/531_basin_list.txt
test_end_date: 30/09/1999
test_start_date: 01/10/1989
train_basin_file: data/531_basin_list.txt
train_end_date: 30/09/2008
train_start_date: 01/10/1999
use_basin_id_encoding: false
validate_every:
validate_n_random_basins: 1
validation_basin_file: data/531_basin_list.txt
validation_end_date: 30/09/1989
validation_start_date: 01/10/1980
